train:
  batch_size: 2048
  lr: 1.99e-3
  weight_decay: 3.41e-5
  hidden_dim: 512
  num_layers: 3
  dropout: 0.2
  static_hidden_dim: 512
  static_out_dim: 256
  head_hidden_dim: 512
  epochs: 13
  num_workers: 6
  precision: bf16

eval:
  batch_size: 2048
